### ISSUE TITLE
Example JSON documentation

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-sandbox#116]
Currently, there is no documentation of example JSONs, whether the examples are available for all the domains and their respective use case or not.

List down all the example JSON for all the available domains and their respective use case.
Confluence page created for populating the information- 

https://fide-official.atlassian.net/wiki/spaces/EC/pages/323911681/Example+JSONs

Make sure that all the links are verified and working if something is not working or needs an enhancement in the example JSON, please put that under the comments column.

This information will be used to create further tickets for the missing examples , endpoints in examples etc.

PLEASE DON'T KEEP LOCAL COPY, KEEP UPDATING THE CONFLUENCE IN BATCHES.

**Comment by rajaneeshk90** [comment]
Updated the sheet with:

- domain
- use cases
- github link for repo
- github link for examples in particular use cases
- checked and updated if the xinput is being used for all the use cases
- checked and updated the endpoints used and not used for all use cases
- provided necessary comments.

**Comment by rajaneeshk90** [comment]
<img width="1579" alt="Screenshot 2024-04-19 at 10 08 27 AM" src="https://github.com/beckn/beckn-sandbox/assets/62893115/62882de2-8747-4886-95e3-8b3d8ce65ba7">

**Comment by rajaneeshk90** [comment]
3 use cases are remaining

**Comment by rajaneeshk90** [comment]
Note: Agrinet had 3 use cases instead of 1 I though it had.

Ppdated the details for Learning, Products and Services use cases of Agrinet.
Updated the details of State Forest Department, Envirogrowth Foundation and Earth Support Initiative use cases of Forest conservation.

**Comment by rajaneeshk90** [comment]
<img width="1073" alt="Screenshot 2024-04-22 at 6 10 31 PM" src="https://github.com/beckn/beckn-sandbox/assets/62893115/4312ff09-29a3-46c3-a3f6-85b87989bd46">
<img width="837" alt="Screenshot 2024-04-22 at 6 10 50 PM" src="https://github.com/beckn/beckn-sandbox/assets/62893115/6c875330-567c-4a52-8b27-494c77674455">

**Comment by rajaneeshk90** [comment]
Closing the ticket.

**Comment by rajaneeshk90** [comment]
Added all the details asked.
