### ISSUE TITLE
Enable Strapi Sandbox 2.0 for dsep:scholarships

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#13]
## Description
Enable the Strapi Sandbox 2.0 environment for the "dsep:scholarships" project. This will involve setting up the sandbox environment, configuring necessary settings, creating catalogs if needed and ensuring it integrates seamlessly with the existing infrastructure.

## Goals
- [x] Set up Strapi Sandbox 2.0 environment.
- [x] Configure sandbox settings to match production environment.
- [x] Check availability of catalogs in strapi.
- [x] Ensure seamless integration with existing infrastructure.
- [x] Test the sandbox environment for stability and performance.

## Expected Outcome
A fully functional Strapi Sandbox 2.0 environment that mirrors the production setup, allowing for safe testing and development without affecting live data.

## Acceptance Criteria
- [x] Strapi Sandbox 2.0 environment is set up and accessible.
- [x] Configuration matches the production environment.
- [x] Integration with existing infrastructure is seamless.
- [x] Catalogs should be present in the strapi 
- [x] Stability and performance tests are passed.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
dsep:scholarships
## Tech Skills Needed
- Strapi configuration and setup
- DevOps skills for environment setup
- Integration testing
- Performance testing

## Complexity
Medium

## Category
Development

## Sub Category
Environment Setup

**Comment by ghost** [comment]
Current Status: The Sandbox 2.0 is created and tested also using postman collection


![Image](https://github.com/user-attachments/assets/6c0402bb-11eb-47fb-8a6d-d2c2f7afa351)
![Image](https://github.com/user-attachments/assets/516008ed-cb0c-4571-a3ee-9842759f484f)
![Image](https://github.com/user-attachments/assets/1498d2b4-1ca3-4174-9c16-81a678c51908)
![Image](https://github.com/user-attachments/assets/1860d8c7-f4eb-4a1b-a8db-94b8cbd13b42)
![Image](https://github.com/user-attachments/assets/b6f37d08-d01b-4c56-8c38-785b3aeb94f4)

**Comment by ghost** [comment]
PC Link - [PC to Main](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/sandbox%202.0/artefects/DSEP/DSEP%20PS%20Sandbox%202.0.postman_collection.json)
