### ISSUE TITLE
Enable Strapi Sandbox 2.0 for dsep:courses

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#14]
## Description
Enable the Strapi Sandbox 2.0 environment for the "dsep:courses" project. This will involve setting up the sandbox environment, configuring necessary settings, creating catalogs if needed and ensuring it integrates seamlessly with the existing infrastructure.

## Goals
- [x] Set up Strapi Sandbox 2.0 environment.
- [x] Configure sandbox settings to match production environment.
- [x] Check availability of catalogs in strapi.
- [x] Ensure seamless integration with existing infrastructure.
- [x] Test the sandbox environment for stability and performance.

## Expected Outcome
A fully functional Strapi Sandbox 2.0 environment that mirrors the production setup, allowing for safe testing and development without affecting live data.

## Acceptance Criteria
- [ ] Strapi Sandbox 2.0 environment is set up and accessible.
- [x] Configuration matches the production environment.
- [ ] Integration with existing infrastructure is seamless.
- [x] Catalogs should be present in the strapi 
- [ ] Stability and performance tests are passed.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
dsep:courses

## Tech Skills Needed
- Strapi configuration and setup
- DevOps skills for environment setup
- Integration testing
- Performance testing

## Complexity
Medium

## Category
Development

## Sub Category
Environment Setup

**Comment by ghost** [comment]
Current Status: The Sandbox 2.0 is created and tested also using postman collection


![Image](https://github.com/user-attachments/assets/23aa4c8e-0de2-4082-a1fc-94ba978d2a7a)
![Image](https://github.com/user-attachments/assets/7caedf30-6dc9-41d1-a3b0-d0c17324eb05)

**Comment by ghost** [comment]
PC Link - [PC to Main](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/sandbox%202.0/artefects/DSEP/DSEP%20PS%20Sandbox%202.0.postman_collection.json)
