### ISSUE TITLE
Enable Strapi Sandbox 2.0 for dsep:jobs

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#15]
## Description
Enable the Strapi Sandbox 2.0 environment for the "dsep:jobs" project. This will involve setting up the sandbox environment, configuring necessary settings, creating catalogs if needed and ensuring it integrates seamlessly with the existing infrastructure.

## Goals
- [x] Set up Strapi Sandbox 2.0 environment.
- [x] Configure sandbox settings to match production environment.
- [x] Check availability of catalogs in strapi.
- [x] Ensure seamless integration with existing infrastructure.
- [x] Test the sandbox environment for stability and performance.

## Expected Outcome
A fully functional Strapi Sandbox 2.0 environment that mirrors the production setup, allowing for safe testing and development without affecting live data.

## Acceptance Criteria
- [x] Strapi Sandbox 2.0 environment is set up and accessible.
- [x] Configuration matches the production environment.
- [x] Integration with existing infrastructure is seamless.
- [x] Catalogs should be present in the strapi 
- [x] Stability and performance tests are passed.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
dsep:jobs

## Tech Skills Needed
- Strapi configuration and setup
- DevOps skills for environment setup
- Integration testing
- Performance testing

## Complexity
Medium

## Category
Development

## Sub Category
Environment Setup

**Comment by ghost** [comment]
Current Status: The Sandbox 2.0 is created and tested also using postman collection

![Image](https://github.com/user-attachments/assets/0818fbd3-7852-4491-9cc9-c8a86aeb5853)
![Image](https://github.com/user-attachments/assets/5837a0ac-c6e9-4745-b59c-b289971351a1)
![Image](https://github.com/user-attachments/assets/6dc4869f-3cb4-44e4-ac39-ec6c456145d6)
![Image](https://github.com/user-attachments/assets/84a2544d-d37b-4c93-9dcf-d2bf2d8a9495)

**Comment by ghost** [comment]
PC Link - [PC to Main](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/sandbox%202.0/artefects/DSEP/DSEP%20PS%20Sandbox%202.0.postman_collection.json)
