### ISSUE TITLE
Enable Strapi Sandbox 2.0 for industry 4.0 - assembly

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#16]
## Description
Enable the Strapi Sandbox 2.0 environment for the "industry 4.0 - assembly" project. This will involve setting up the sandbox environment, configuring necessary settings, creating catalogs if needed and ensuring it integrates seamlessly with the existing infrastructure.

## Goals
- [x] Set up Strapi Sandbox 2.0 environment.
- [x] Configure sandbox settings to match production environment.
- [x] Check availability of catalogs in strapi.
- [x] Ensure seamless integration with existing infrastructure.
- [x] Test the sandbox environment for stability and performance.

## Expected Outcome
A fully functional Strapi Sandbox 2.0 environment that mirrors the production setup, allowing for safe testing and development without affecting live data.

## Acceptance Criteria
- [x] Strapi Sandbox 2.0 environment is set up and accessible.
- [x] Configuration matches the production environment.
- [x] Integration with existing infrastructure is seamless.
- [x] Catalogs should be present in the strapi 
- [x] Stability and performance tests are passed.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
industry 4.0 - assembly

## Tech Skills Needed
- Strapi configuration and setup
- DevOps skills for environment setup
- Integration testing
- Performance testing

## Complexity
Medium

## Category
Development

## Sub Category
Environment Setup

**Comment by ghost** [comment]
Current Status: The Sandbox 2.0 is created and tested also using postman collection

![Image](https://github.com/user-attachments/assets/a4a34576-0b23-4492-a6f9-d48166ee47f7)
![Image](https://github.com/user-attachments/assets/171a4465-1f46-4d12-bcd2-5d0402c0d1d0)
![Image](https://github.com/user-attachments/assets/d7208589-9e55-4c55-92a1-5fcb5ed74541)
![Image](https://github.com/user-attachments/assets/efafa6d4-2be1-44e9-a988-18347276eb3a)

**Comment by shreyvishal** [comment]
Current Status: The Sandbox 2.0 is created and tested also using postman collection

![Image](https://github.com/user-attachments/assets/6df5dece-666b-4739-b860-b475df9f4355)
![Image](https://github.com/user-attachments/assets/dece90f4-6492-44a1-87b3-51ab9fd882f9)
![Image](https://github.com/user-attachments/assets/767340a5-e60c-40af-af48-a67e70c77cf8)
![Image](https://github.com/user-attachments/assets/16119d71-577e-492b-ac7c-1e7f7b2071fe)

**Comment by ghost** [comment]
PC Link - [PC](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/sandbox%202.0/artefects/Industry4.0/Industry-4.0%20PS%20Sandbox%202.0.postman_collection.json)
