### ISSUE TITLE
Setup Strapi in BOC Environment

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#29]
## Description
Set up a Strapi instance in the BOC environment to enable content management and API functionalities as required by the application. 

## Goals
- [x] Install and configure Strapi in the BOC environment.
- [x] Connect Strapi to the appropriate database for content management.
- [x] Configure environment variables and settings for seamless operation in the BOC environment.

## Expected Outcome
A fully configured Strapi instance in the BOC environment, ready to handle content management and API needs as specified by the BOC team.

## Acceptance Criteria
- [x] Strapi is installed and configured in the BOC environment.
- [x] Database connection is established, and Strapi can manage content data effectively.
- [x] Environment variables and settings are correctly configured for the BOC environment.
- [x] Testing confirms that Strapi functions as expected within the BOC environment, with all required APIs operational.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
BOC Environment

## Tech Skills Needed
- Strapi Setup and Configuration
- Database Configuration
- Environment Variable Management
- Backend Testing and Verification

## Complexity
Medium

## Category
Infrastructure Setup

## Sub Category
Strapi Installation

**Comment by em-tpt-bbandi** [comment]
Setuped Strapi BPP PS in BOC Environment.

created a new t2.medium instance 
![image](https://github.com/user-attachments/assets/7765745a-0e25-4b2b-be65-66f3fdae370a)


deployed BPP-PS using Beckn-onix 
![image](https://github.com/user-attachments/assets/7439261e-9409-4f1b-a933-eb9308e7a94d)

deployed bpp-strapi.
![image](https://github.com/user-attachments/assets/6316904f-d93c-42db-a047-446ff3889924)

done DNS configuration for BPP & STRAPI.
![image](https://github.com/user-attachments/assets/47be7885-e36e-47fb-bc26-dd5f5131ec36)

done Nginx configuration for BPP & STRAPI.
![image](https://github.com/user-attachments/assets/4928e861-6295-4438-9a0d-f1f36f3181a9)
![image](https://github.com/user-attachments/assets/8cd6354c-ad7b-4e02-8df4-c0d3484efc37)
![image](https://github.com/user-attachments/assets/cdc40b2a-96e0-418a-ab0b-716f5a477205)

Applications are publically accessable.
1: bpp-ps-client-strapi.becknprotocol.io
2: bpp-ps-network-strapi.becknprotocol.io
3: bpp-unified-strapi.becknprotocol.io
