### ISSUE TITLE
Testing for Enabling GenAI Sandbox for DHP Diagnostics

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#37]
## Description
Conduct end-to-end QA testing for the GenAI Sandbox environment tailored to the DHP  Diagnostics use case. Validate key workflows, ensure catalogue generation using GenAI, and verify the accuracy and structure of JSON responses for on_action calls.

## Goals
- [x] Perform end-to-end QA for the GenAI Sandbox for DHP Diagnostics.
- [x] Verify if the catalogue is generated using GenAI, and flag if it is missing.
- [x] Validate the JSON responses for on_action calls to ensure accuracy and structure.

## Expected Outcome
A validated GenAI Sandbox environment for DHP Diagnostics with seamless functionality, accurate catalogue generation, and correct JSON responses.

## Acceptance Criteria
- [x] End-to-end QA testing is completed and documented.
- [x] Catalogue is generated using GenAI or issues are flagged.
- [x] JSON responses for on_action calls are validated and confirmed accurate.
- [x] No critical issues remain, and test results are documented.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
GenAI Integration, QA Testing, JSON Validation, Workflow Testing

## Complexity
Medium

## Category
Testing

## Sub Category
Sandbox Validation

**Comment by omkar-em** [comment]
![Image](https://github.com/user-attachments/assets/719f959c-90af-4654-99e0-371364340483)

**Comment by omkar-em** [comment]
Application tested but there is a blocker - 
https://github.com/beckn/beckn-ui-workspace/issues/2827

Will resume testing once blocker is removed.
Closing this task.
cc: @shreyvishal @emmayank @PritiEM @SanketEminds
