### ISSUE TITLE
Testing for Enabling GenAI Sandbox for Industry 4.0

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#38]
## Description
Conduct end-to-end QA testing for the GenAI Sandbox environment tailored to the Industy 4.0 use case. Validate key workflows, ensure catalogue generation using GenAI, and verify the accuracy and structure of JSON responses for on_action calls.

## Goals
- [x] Perform end-to-end QA for the GenAI Sandbox for Industy 4.0.
- [x] Verify if the catalogue is generated using GenAI, and flag if it is missing.
- [x] Validate the JSON responses for on_action calls to ensure accuracy and structure.

## Expected Outcome
A validated GenAI Sandbox environment for Industy 4.0 with seamless functionality, accurate catalogue generation, and correct JSON responses.

## Acceptance Criteria
- [x] End-to-end QA testing is completed and documented.
- [x] Catalogue is generated using GenAI or issues are flagged.
- [x] JSON responses for on_action calls are validated and confirmed accurate.
- [x] No critical issues remain, and test results are documented.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
GenAI Integration, QA Testing, JSON Validation, Workflow Testing

## Complexity
Medium

## Category
Testing

## Sub Category
Sandbox Validation

**Comment by omkar-em** [comment]
Positive scenarios
![Image](https://github.com/user-attachments/assets/de86be84-b287-4b0d-9df0-55918eca8d7e)
![Image](https://github.com/user-attachments/assets/aa8f9c08-cfe9-4ce9-8cdd-a2191ec75fc5)
![Image](https://github.com/user-attachments/assets/9438b273-41dd-4df3-8160-bb606d8c0313)
![Image](https://github.com/user-attachments/assets/0817bd85-10be-45dc-b171-4957aeff7acf)
![Image](https://github.com/user-attachments/assets/998b2237-402a-4684-b786-c035e786cb05)

Negative Scenario -

Wrong method-
![Image](https://github.com/user-attachments/assets/4893a38a-f5b9-4ec8-b8bd-3b6d294fba3e)
![Image](https://github.com/user-attachments/assets/07460833-4590-4bd3-a9d7-41db0922436d)
![Image](https://github.com/user-attachments/assets/4b5927e4-6d65-4460-b2b1-1903eb08ce09)
![Image](https://github.com/user-attachments/assets/5587c058-ea59-4709-8034-0b2e47b1a438)

**Comment by omkar-em** [comment]
Testing is completed for serach, select, init but facing issue in subsequent apis.

https://github.com/beckn/beckn-ui-workspace/issues/2826

Will test again once issue is resolved.
Proceeding to close this task.

cc: @emmayank @shreyvishal @PritiEM @SanketEminds
