### ISSUE TITLE
Testing for Enabling GenAI Sandbox for ODR

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#39]
## Description
Conduct end-to-end QA testing for the GenAI Sandbox environment tailored to the ODR use case. Validate key workflows, ensure catalogue generation using GenAI, and verify the accuracy and structure of JSON responses for on_action calls.

## Goals
- [x] Perform end-to-end QA for the GenAI Sandbox for ODR .
- [x] Verify if the catalogue is generated using GenAI, and flag if it is missing.
- [x] Validate the JSON responses for on_action calls to ensure accuracy and structure.

## Expected Outcome
A validated GenAI Sandbox environment for ODR with seamless functionality, accurate catalogue generation, and correct JSON responses.

## Acceptance Criteria
- [x] End-to-end QA testing is completed and documented.
- [x] Catalogue is generated using GenAI or issues are flagged.
- [x] JSON responses for on_action calls are validated and confirmed accurate.
- [x] No critical issues remain, and test results are documented.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
GenAI Integration, QA Testing, JSON Validation, Workflow Testing

## Complexity
Medium

## Category
Testing

## Sub Category
Sandbox Validation

**Comment by SanketEminds** [comment]
Testing for enabling GenAI Sandbox for ODR has been successfully completed. The feature is now active and working as expected. Closing this issue.

Positive scenarios:
![Image](https://github.com/user-attachments/assets/12df964b-35f5-4d41-8bf0-637f0bce0f79)
![Image](https://github.com/user-attachments/assets/9d8df986-a639-4336-9e17-9fe8e71abf88)
![Image](https://github.com/user-attachments/assets/8fb9fe42-ae12-4da8-9c8f-7d21d75eabf7)
![Image](https://github.com/user-attachments/assets/f0b25d15-2637-4033-8c68-4411677de7fb)
![Image](https://github.com/user-attachments/assets/01ce3f89-f11d-452e-8cb5-7f8c8a1e7fc7)
![Image](https://github.com/user-attachments/assets/308dc534-1550-4a86-9589-e86919e7b368)
![Image](https://github.com/user-attachments/assets/bbfeb9bd-c782-4f4c-ad7e-2f43037c24f1)
![Image](https://github.com/user-attachments/assets/cd516165-29e3-4616-913e-40667e01d3bf)

Negative Scenarios:
![Image](https://github.com/user-attachments/assets/1bf21bd1-81a5-4b17-bee1-ff76e69c8f9f)
![Image](https://github.com/user-attachments/assets/ba4264d8-265e-407f-ab66-159169178ad6)
![Image](https://github.com/user-attachments/assets/28076743-bd7b-4aca-bb08-ae474b9969bf)
closing this task.

cc: @omkar-em @shreyvishal @emmayank @PritiEM

**Comment by omkar-em** [comment]
Verified.
Closing this task.

cc: @emmayank @PritiEM @SanketEminds
