### ISSUE TITLE
Testing for Enabling GenAI Sandbox for UEI: EV

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#40]
## Description
Conduct end-to-end QA testing for the GenAI Sandbox environment tailored to the UEI: EV use case. Validate key workflows, ensure catalogue generation using GenAI, and verify the accuracy and structure of JSON responses for on_action calls.

## Goals
- [x] Perform end-to-end QA for the GenAI Sandbox for UEI: EV.
- [x] Verify if the catalogue is generated using GenAI, and flag if it is missing.
- [x] Validate the JSON responses for on_action calls to ensure accuracy and structure.

## Expected Outcome
A validated GenAI Sandbox environment for UEI: EV with seamless functionality, accurate catalogue generation, and correct JSON responses.

## Acceptance Criteria
- [x] End-to-end QA testing is completed and documented.
- [x] Catalogue is generated using GenAI or issues are flagged.
- [x] JSON responses for on_action calls are validated and confirmed accurate.
- [x] No critical issues remain, and test results are documented.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
GenAI Integration, QA Testing, JSON Validation, Workflow Testing

## Complexity
Medium

## Category
Testing

## Sub Category
Sandbox Validation

**Comment by omkar-em** [comment]
Testing for enabling GenAI Sandbox for UEI: EV has been successfully completed. The feature is now active and working as expected. Closing this issue.

Positive scenarios

![Image](https://github.com/user-attachments/assets/f953b526-880a-4421-bcda-3cb3b956d8e7)
![Image](https://github.com/user-attachments/assets/5db0cea6-109c-409f-9b97-78a08554a1cc)
![Image](https://github.com/user-attachments/assets/56f22f87-92cb-4764-bc9b-cbbc1b36d7e0)
![Image](https://github.com/user-attachments/assets/a5bf61eb-d498-425f-a5b3-af5e1f5a6a32)
![Image](https://github.com/user-attachments/assets/78e24e6d-b0eb-4570-ac09-30b8ded9148e)
![Image](https://github.com/user-attachments/assets/a8095648-ed5c-44f1-9e7c-2adccf220e5e)
![Image](https://github.com/user-attachments/assets/11bb7dd8-74af-4a97-a410-65d66f6cf702)


Negative Scenario -

1. Wrong method
![Image](https://github.com/user-attachments/assets/8739b315-afb2-45d7-af79-9c60eff2df87)
![Image](https://github.com/user-attachments/assets/90cac772-100c-4b73-a94d-31a68d50990e)
![Image](https://github.com/user-attachments/assets/a5d9c3b2-5b1b-48ad-9c7a-25b01cb54dfe)
![Image](https://github.com/user-attachments/assets/7e54768b-493f-4c29-9229-4087cfb14b0d)
![Image](https://github.com/user-attachments/assets/c0c47f0d-b847-4bb0-b8ef-bc8685e9a496)
![Image](https://github.com/user-attachments/assets/74d68dc0-cc57-4f8d-9f8e-9e3b1574dc5a)
![Image](https://github.com/user-attachments/assets/bfa32f7a-784b-4c4b-8294-4723c2903511)
![Image](https://github.com/user-attachments/assets/55bd6a9d-1c5d-4abc-a507-3b293f204cce)


2. Invalid Method -
![Image](https://github.com/user-attachments/assets/8c829878-b793-480e-875f-a1e5e0f6d35c)
![Image](https://github.com/user-attachments/assets/b193d1af-3752-4139-b184-da8d7e7aed45)
![Image](https://github.com/user-attachments/assets/c01226a9-8ad6-4d44-875e-9f63205363df)
![Image](https://github.com/user-attachments/assets/50186ac7-547f-4d58-92a7-ae6bf194b59c)
![Image](https://github.com/user-attachments/assets/a16e19f2-d4a0-45c5-8aed-abe81ae6d7f5)
![Image](https://github.com/user-attachments/assets/af687851-c62c-4759-9d12-58e05c5cffff)

Proceeding to close this task.

cc: @PritiEM @emmayank
