### ISSUE TITLE
Testing for Enabling GenAI Sandbox for DHP Pharmacy

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-sandbox#42]
## Description
Conduct end-to-end QA testing for the GenAI Sandbox environment tailored to the DHP Pharmacy use case. Validate key workflows, ensure catalogue generation using GenAI, and verify the accuracy and structure of JSON responses for on_action calls.

## Goals
- [x] Perform end-to-end QA for the GenAI Sandbox for DHP Pharmacy.
- [x] Verify if the catalogue is generated using GenAI, and flag if it is missing.
- [x] Validate the JSON responses for on_action calls to ensure accuracy and structure.

## Expected Outcome
A validated GenAI Sandbox environment for DHP Pharmacy with seamless functionality, accurate catalogue generation, and correct JSON responses.

## Acceptance Criteria
- [x] End-to-end QA testing is completed and documented.
- [x] Catalogue is generated using GenAI or issues are flagged.
- [x] JSON responses for on_action calls are validated and confirmed accurate.
- [x] No critical issues remain, and test results are documented.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
GenAI Integration, QA Testing, JSON Validation, Workflow Testing

## Complexity
Medium

## Category
Testing

## Sub Category
Sandbox Validation

**Comment by omkar-em** [comment]
Testing for enabling GenAI Sandbox for DHP: Pharmacy has been successfully completed. The feature is now active and working as expected. Closing this issue.

Positive scenarios
![image](https://github.com/user-attachments/assets/83f240f7-78cf-44cb-ba97-eaaec531b812)
![image](https://github.com/user-attachments/assets/922fdf9a-b730-4f90-b4e5-20dcce6042ac)
![image](https://github.com/user-attachments/assets/148a4b4a-3c54-4499-8395-3ae310f2fae4)
![image](https://github.com/user-attachments/assets/540f6c0e-4371-47dc-a288-9d4d9bf9a638)
![image](https://github.com/user-attachments/assets/9da37f74-8244-4898-adc6-31b36131b423)
![image](https://github.com/user-attachments/assets/583e30bc-ce5c-488a-af61-bdf52a8ff8fc)
![image](https://github.com/user-attachments/assets/8e66ed07-2abc-43a0-a318-7dc5db90a7ef)


Negative Scenarios-

1. Wrong method
![image](https://github.com/user-attachments/assets/b9df19ce-ee94-4483-a45d-2fe05263e954)
![image](https://github.com/user-attachments/assets/56426323-6f1f-4fde-a5b0-386d4fb9b0b0)
![image](https://github.com/user-attachments/assets/b8ec74ce-56a9-4432-96f8-865eccc09d48)
![image](https://github.com/user-attachments/assets/fb0b7449-9a6a-4ca2-be83-b33dbb46d78f)


cc: @PritiEM @emmayank @shreyvishal
