### ISSUE TITLE
Inconsistency in ODR artifacts 

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-sandbox#97]
## Description

ODR artifacts in the repository (https://github.com/beckn/beckn-sandbox/tree/main/artefacts/ODR) are not in line with the core specifications. It was found during the testing of the BPP plugin. 

1. Search: In the specification, the provider object is inside the catalog, but in artifacts it is outside the catalog.
2. Confirm: The fulfillment structure is incorrect. According to the specification, the contact should also be a part of the customer.

Apart from these, there may be some other issues when compared to core specs. A thorough testing comparison with the core specs is required.

## Goals

- [ ] ODR artifacts should be consistent with the core specification.

## Expected Outcome

ODR artifacts should be corrected and verified to follow the core specifications.

## Acceptance Criteria

- [ ] Updated ODR artifacts according to core specifications.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

beckn-sandbox

### Project Name

beckn-sandbox

### Tech Skills Needed:

beckn specifications
postman
JSON

### Complexity

Pick one of [High]/[Medium]/[Low]

### Category

Specifications

### Sub Category

ODR

**Comment by rajaneeshk90** [comment]
@vishi24 please assign this task to me. Will make the change. 

Thanks,
Rajaneesh

**Comment by rajaneeshk90** [comment]
Closing the issue.
