### ISSUE TITLE
Combine webhook source code in beckn-sandbox source code

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-sandbox#99]
## Description

Currently, the Beckn Sandbox and Webhook stand as distinct applications. However, since the Webhook predominantly comprises static functionalities we can consolidate the beckn-sandbox and webhook applications into a single, unified application. This consolidation aims to streamline development, maintenance, and hosting efforts while potentially improving efficiency and reducing resource utilization.

1. Feasibility Assessment: Conduct a thorough assessment to determine the technical feasibility and potential challenges associated with the proposed merger.
2. Impact Analysis: Evaluate the potential impact on existing functionalities, development workflows, and deployment processes.

Merge the webhook code into the beckn sandbox code.

## Goals

- [ ] Merge the webhook code into the beckn sandbox code.

## Expected Outcome

When the webhook is merged into the sandbox and the deployment is done there should not be need of webhook and sandbox should work as expected.

## Acceptance Criteria

- [ ] Fully functional sandbox with webhook code merged.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

beckn-sandbox

### Project Name

beckn-sandbox

### Tech Skills Needed:

node js

### Complexity

Medium

### Category

Specifications

**Comment by vbabuEM** [comment]
Migrated and updated the documentation in PR https://github.com/beckn/beckn-sandbox/pull/121
